language: node_js
node_js:
  - "7.0.0"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "gulp dev-ci"
  - "gulp test"
install:
  - "npm install"
  - "npm install bower -g"
  - "bower install"
